#db-setup
# writer
spring.datasource.url.readWrite=jdbc:mysql://localhost:3306/HomefirstOne?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Hffc@123

#reader
spring.datasource.url.readOnly=jdbc:mysql://localhost:3306/HomefirstOne?createDatabaseIfNotExist=true
spring.datasource.rUsername=root
spring.datasource.rPassword=Hffc@123

#Server config
server.port=8010

#Flags
application.flags.isSalesforceLive=false
application.flags.isStrictProduction=true

#File paths
application.path.files=/Users/User/Documents/tanya/
application.path.fileIdentifierURL=http://localhost:4200/document/?fid=
application.path.smsDispositionURL=https://webhook.site/6b1c7976-100d-473e-97e9-94eb51cc2bba?
application.path.pulseCallDispositionURL=https://one.homefirstindia.com:8443/hfo/public/v1/Pulse.callDisposition?

#Fullcopy
application.salesforce.username=utility.user@homefirstindia.com.fullcopy
application.salesforce.url=https://test.salesforce.com
application.salesforce.clientID=3MVG9duA.sPEm7m8XuHOjfLjtiOXORurECOOcZCsuqeU3HCWpEeMfjF0IJSUwu0HOtIs3mAwLNbUfmTQIq9wp

#Scheduler
application.key.runScheduler=false
application.key.backupLog=false