#db-setup
spring.datasource.url=${DB_URL_UAT:jdbc:mysql://localhost:3306/HomefirstOne?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}
spring.datasource.username=${DB_USERNAME_UAT:root}
spring.datasource.password=${DB_PASSWORD_UAT:Hffc@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Server config
server.port=${SERVER_PORT_UAT:8443}

#Flags
application.flags.isSalesforceLive=false
application.flags.isStrictProduction=false

app.seed.enabled=false
app.upload.dir=${UPLOAD_DIR_UAT:./uploads}

