spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/HomefirstOne?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=local-vaultlink-super-secret-jwt-key-2026-very-secure
app.cors.allowed-origins[0]=http://localhost:4200
app.cors.allowed-origins[1]=http://localhost:4201
app.seed.enabled=true
app.seed.username=admin
app.seed.password=Admin@123
app.seed.full-name=VaultLink Admin

logging.level.com.vaultlink=DEBUG


application.salesforce.username=api.user@homefirstindia.com.homefirst
application.salesforce.url=https://test.salesforce.com
application.salesforce.clientID=3MVG9duA.sPEm7m.Tyel5Uii81JA.1UibQceQfRu9fry_FN1Yl9YThsf5T2HUawCnnrXVRwGN5G6qA9US1e3_
